# Generated by Django 4.1.2 on 2022-10-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagedata",
            name="english_info",
        ),
        migrations.RemoveField(
            model_name="mainpagedata",
            name="persian_info",
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="about_page_navid_motor_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن معرفی شرکت نوید موتور"
            ),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="about_page_pumpiran_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن معرفی گروه پمپ ایران"
            ),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="about_us_why_navid_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن تبلیغاتی کارت تیپ و مدل"
            ),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="about_us_why_navid_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن تبلیغاتی کارت خدمات پس از فروش"
            ),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="about_us_why_navid_3",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="متن تبلیغاتی کارت مواد اولیه با کیفیت",
            ),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="main_page_english_info",
            field=models.TextField(blank=True, null=True, verbose_name="مقدمه انگلیسی"),
        ),
        migrations.AddField(
            model_name="mainpagedata",
            name="main_page_persian_info",
            field=models.TextField(blank=True, null=True, verbose_name="مقدمه فارسی"),
        ),
    ]
