# Generated by Django 4.1.2 on 2022-10-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_mainpagedata_english_info_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainPageData",
            new_name="SiteData",
        ),
    ]
