# Generated by Django 4.1.2 on 2022-10-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_mainpagedata_sitedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedata",
            name="data_set_name",
            field=models.CharField(default="نام مجموعه داده", max_length=200),
        ),
    ]
