# Generated by Django 4.1.2 on 2022-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitedata_data_set_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteDataKeyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=200, verbose_name="نام متن مورد نظر"),
                ),
                ("value", models.TextField()),
            ],
        ),
    ]
