# Generated by Django 4.1.2 on 2022-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_sitedata_alter_sitedatakeyvalue_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedatakeyvalue",
            name="key",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="نام متن مورد نظر"
            ),
        ),
    ]
