# Generated by Django 4.1.2 on 2022-10-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_contactusform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUsForm",
        ),
    ]
