# Generated by Django 4.1.2 on 2022-10-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_contactusform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactUsForm",
            new_name="ContactUsFormModel",
        ),
    ]
