# Generated by Django 4.1.2 on 2022-11-05 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_contactusformmodel_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactusformmodel",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
