# Generated by Django 4.1.2 on 2022-11-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_contactusformmodel_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactusformmodel",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
