# Generated by Django 4.1.7 on 2023-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_city_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedatakeyvalue",
            name="language",
            field=models.CharField(
                choices=[("fa", "فارسی"), ("en", "انگلیسی"), ("ar", "عربی")],
                default="fa",
                max_length=7,
            ),
        ),
    ]
