# Generated by Django 4.1.7 on 2023-03-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("En", "English"),
                            ("Fa", "Persian"),
                            ("Ar", "Arabic"),
                        ],
                        default="Fa",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("owner_name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("telephone", models.CharField(blank=True, max_length=11, null=True)),
                ("mobile", models.CharField(blank=True, max_length=11, null=True)),
                ("fax", models.CharField(blank=True, max_length=11, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.province",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "agencies",
            },
        ),
    ]
