# Generated by Django 4.1.2 on 2022-10-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0003_alter_cities_name_alter_provinces_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cities",
        ),
        migrations.DeleteModel(
            name="Provinces",
        ),
    ]
