# Generated by Django 4.1.2 on 2022-11-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0013_remove_contactusformmodel_city"),
        ("salesnetwork", "0004_delete_cities_delete_provinces"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("En", "English"),
                            ("Fa", "Persian"),
                            ("Ar", "Arabic"),
                        ],
                        default="Fa",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("owner_name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("telephone", models.BigIntegerField(blank=True, null=True)),
                ("mobile", models.BigIntegerField(blank=True, null=True)),
                ("fax", models.BigIntegerField(blank=True, null=True)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "city",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.province",
                    ),
                ),
            ],
        ),
    ]
