# Generated by Django 4.1.2 on 2022-11-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="longitude",
        ),
    ]
