# Generated by Django 4.1.2 on 2022-11-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0007_agency_latitude_agency_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="longitude",
        ),
    ]
