# Generated by Django 4.1.2 on 2022-11-06 09:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0009_agency_latitude_agency_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
