# Generated by Django 4.1.2 on 2022-11-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0010_agency_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="location",
        ),
    ]
