# Generated by Django 4.1.2 on 2022-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesnetwork", "0011_remove_agency_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="fax",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="mobile",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="telephone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
