# Generated by Django 4.1.2 on 2022-12-01 09:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name_fa",
                    models.CharField(max_length=255, verbose_name="نام فارسی مدل"),
                ),
                (
                    "model_name_en",
                    models.CharField(max_length=255, verbose_name="نام انگلیسی مدل"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_model_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_model_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_name_fa",
                    models.CharField(max_length=255, verbose_name="نام فارسی کاربرد"),
                ),
                (
                    "usage_name_en",
                    models.CharField(max_length=255, verbose_name="نام انگلیسی کاربرد"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PumpType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type_name", models.CharField(max_length=255, verbose_name="نام مدل")),
                (
                    "description_fa",
                    models.TextField(verbose_name="مشخصات فنی تیپ به فارسی"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="مشخصات فنی تیپ به انگلیسی"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pump_type_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pump_type_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pump_name",
                    models.CharField(max_length=255, verbose_name="نام محصول"),
                ),
                (
                    "pump_image",
                    models.ImageField(
                        help_text="تصویر الکتروپمپ",
                        upload_to=products.models.path_and_rename_image,
                        verbose_name="تصویر الکتروپمپ",
                    ),
                ),
                (
                    "NPSH_diagram_image",
                    models.ImageField(
                        help_text="نمودار NPSH",
                        upload_to=products.models.path_and_rename_image,
                        verbose_name="نمودار NPSH",
                    ),
                ),
                (
                    "power_diagram_image",
                    models.ImageField(
                        help_text="نمودار توان",
                        upload_to=products.models.path_and_rename_image,
                        verbose_name="نمودار توان",
                    ),
                ),
                ("max_head", models.FloatField()),
                ("max_flow", models.FloatField()),
                (
                    "head_flow_dataset",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(blank=True, null=True), size=2
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "motor_ph",
                    models.CharField(
                        blank=True,
                        choices=[("1 ph", "1 ph"), ("3 ph", "3ph")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "motor_rpm",
                    models.CharField(
                        blank=True,
                        choices=[("1450 rpm", "1450 rpm"), ("2900 rpm", "2900 rpm")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "pump_technical_datasheet_fa",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "pump_technical_datasheet_en",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.mainmodel",
                        verbose_name="نام مدل اصلی پمپ",
                    ),
                ),
                (
                    "pump_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.pumptype",
                        verbose_name="تیپ پمپ",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.usage",
                        verbose_name="کاربرد",
                    ),
                ),
            ],
        ),
    ]
