# Generated by Django 4.1.2 on 2022-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="motor_ph",
            field=models.CharField(
                blank=True,
                choices=[("1 ph", "1 ph"), ("3 ph", "3 ph")],
                max_length=4,
                null=True,
            ),
        ),
    ]
