# Generated by Django 4.1.2 on 2022-12-03 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_alter_product_head_flow_dataset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sub_usage_name_fa",
                    models.CharField(
                        max_length=255, verbose_name="نام فارسی کاربرد جزئی"
                    ),
                ),
                (
                    "sub_usage_name_en",
                    models.CharField(
                        max_length=255, verbose_name="نام انگلیسی کاربرد جزئی"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_usage_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_usage_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.usage"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sub_usage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.subusage",
                verbose_name="کاربرد جزئی",
            ),
        ),
    ]
