# Generated by Django 4.1.2 on 2022-12-03 12:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_subusage_product_sub_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmodel",
            name="model_image",
            field=models.ImageField(
                default="images/building.png",
                help_text="تصویر مدل الکتروپمپ",
                upload_to=products.models.path_and_rename_image,
                verbose_name="تصویر مدل الکتروپمپ",
            ),
        ),
        migrations.AddField(
            model_name="usage",
            name="usage_image",
            field=models.ImageField(
                default="images/building.png",
                help_text="تصویر کاربرد",
                upload_to=products.models.path_and_rename_image,
                verbose_name="تصویر کاربرد",
            ),
        ),
    ]
