# Generated by Django 4.1.2 on 2022-12-03 13:20

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_mainmodel_model_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmodel",
            name="model_image",
            field=models.ImageField(
                help_text="تصویر مدل الکتروپمپ",
                upload_to=products.models.path_and_rename_image,
                verbose_name="تصویر مدل الکتروپمپ",
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="usage_image",
            field=models.ImageField(
                help_text="تصویر کاربرد",
                upload_to=products.models.path_and_rename_image,
                verbose_name="تصویر کاربرد",
            ),
        ),
    ]
