# Generated by Django 4.1.2 on 2022-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_remove_product_head_flow_dataset_headflowdataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="usage_name_en",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام انگلیسی کاربرد"
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="usage_name_fa",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام فارسی کاربرد"
            ),
        ),
    ]
