# Generated by Django 4.1.2 on 2022-12-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_usage_usage_name_en_alter_usage_usage_name_fa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmodel",
            name="model_name_en",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام انگلیسی مدل"
            ),
        ),
        migrations.AlterField(
            model_name="mainmodel",
            name="model_name_fa",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام فارسی مدل"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pump_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="نام محصول"
            ),
        ),
        migrations.AlterField(
            model_name="pumptype",
            name="main_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.mainmodel",
                verbose_name="مدل اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="pumptype",
            name="type_name",
            field=models.CharField(max_length=255, verbose_name="نام تیپ"),
        ),
        migrations.AlterField(
            model_name="subusage",
            name="usage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.usage",
                verbose_name="کاربرد اصلی",
            ),
        ),
    ]
