# Generated by Django 4.1.2 on 2022-12-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_mainmodel_model_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="headflowdataset",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="headflowdataset",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="headflowdataset",
            name="last_updated_at",
        ),
        migrations.RemoveField(
            model_name="headflowdataset",
            name="last_updated_by",
        ),
        migrations.AlterField(
            model_name="product",
            name="motor_rpm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1450 rpm", "1450 rpm"),
                    ("2900 rpm", "2900 rpm"),
                    ("2800 rpm", "2800 rpm"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
